### ISSUE TITLE
readme for docker

### ISSUE THREAD

**Issue by yashtibrewal** [yashtibrewal/leechcode#12]
Hi @harlsh 
could you please add a guide to run docker after installing it?
I am having difficulty running it.

Thanks

**Comment by harlsh** [comment]
I already added it in the readme. Please double check before raising an issue.
![image](https://user-images.githubusercontent.com/20385352/151719416-22a1a076-b634-4861-b676-533fafff8c8b.png)

**Comment by yashtibrewal** [comment]
Thank you for pointing it out.
