### ISSUE TITLE
docker not building

### ISSUE THREAD

**Issue by yashtibrewal** [yashtibrewal/leechcode#13]
failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c go build -o /docker-leechcode]: exit code: 1

I am unable to solve this issue.

**Comment by yashtibrewal** [comment]
Issue raised on the commit 5152b208eebc04f3d23396d9eb1011ffe1ade4b4

**Comment by harlsh** [comment]
Fixed it f03614134263189b3aa3538ba752f9814007234b
