### ISSUE TITLE
Provide a POST endpoint, where users can submit their solution(code)

### ISSUE THREAD

**Issue by yashtibrewal** [yashtibrewal/leechcode#4]
As a user I should be able to submit my solution and fetch the results for the solution.

**Comment by yashtibrewal** [comment]
Stuck because I cannot figure out the docker network setup as of now.

**Comment by harlsh** [comment]
End point for code execution uses the following struct. 
Just pass in following to `/api/v1/execute`

type Solution struct {
	gorm.Model
	UserId    string `json:"user_id" gorm:"foreignKey:ID;references:User;"`
	Language  string `json:"language"`
	Version   string `json:"version"` // can be empty
	Code      string `json:"code"`
}
